title: TCESE 2023
description: Technion Chemical Engineering Student Conference 2023
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Navigation
nav:
  - title: Home
    url: /
  - title: Calls For Participants
    url: /call-for-Participants/
  - title: Program Schedule
    url: /program-schedule/
